// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUGCPlGwXZoytnFVbXDFZXar242d01pLQ',
    appId: '1:998685125958:web:de5ae57d32fd8f652d4947',
    messagingSenderId: '998685125958',
    projectId: 'alera-a0132',
    authDomain: 'alera-a0132.firebaseapp.com',
    storageBucket: 'alera-a0132.firebasestorage.app',
    measurementId: 'G-HSB0R43X1Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjPCDCq3GBug-qm3oFtHd8aYY4kDP3BaA',
    appId: '1:998685125958:android:d5b0bf26559048332d4947',
    messagingSenderId: '998685125958',
    projectId: 'alera-a0132',
    storageBucket: 'alera-a0132.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQyDKJlbiqcuS60PjpDAjXHz1Oi3go6cI',
    appId: '1:998685125958:ios:3798b82bed47f4472d4947',
    messagingSenderId: '998685125958',
    projectId: 'alera-a0132',
    storageBucket: 'alera-a0132.firebasestorage.app',
    iosBundleId: 'com.example.alera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQyDKJlbiqcuS60PjpDAjXHz1Oi3go6cI',
    appId: '1:998685125958:ios:3798b82bed47f4472d4947',
    messagingSenderId: '998685125958',
    projectId: 'alera-a0132',
    storageBucket: 'alera-a0132.firebasestorage.app',
    iosBundleId: 'com.example.alera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUGCPlGwXZoytnFVbXDFZXar242d01pLQ',
    appId: '1:998685125958:web:eccb2e1b214f18682d4947',
    messagingSenderId: '998685125958',
    projectId: 'alera-a0132',
    authDomain: 'alera-a0132.firebaseapp.com',
    storageBucket: 'alera-a0132.firebasestorage.app',
    measurementId: 'G-CD81T3W49N',
  );
}
